# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    #crashlytics

    firebase_app_distribution(
          app: "1:591223998749:android:84ca24a11c167fa50ef9f4",
          groups: "azap",
          release_notes: "Lots of amazing new features to test out!",
          apk_path: "../build/app/outputs/apk/release/app-release.apk",
          firebase_cli_token: $firebase_cli_token
      )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

end
